name: "Set trending labels"
on:
  issue_comment:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: HugoCL/aws-git-trending-action@main
        with:
          quantity: 1
          included-labels: "[ bug ]"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
    timeout-minutes: 20
